"""
Analytics Dashboard - Unified Reporting Script

Generates comprehensive analytics dashboard combining all analysis scripts.
Creates a formatted markdown report for easy review.
"""

import pandas as pd
from datetime import datetime
from pathlib import Path
import subprocess
import sys

# Import other analytics modules
try:
    import trade_ideas_analytics as trade_analytics
    import news_analytics
    import cross_repository_analytics as cross_analytics
except ImportError:
    print("⚠️ Warning: Could not import all analytics modules")
    print("Make sure all analytics scripts are in the same directory")


def generate_markdown_report(output_dir="../analytics_reports"):
    """Generate comprehensive markdown analytics report"""
    
    # Create output directory if it doesn't exist
    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True)
    
    # Report filename with timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d")
    report_file = output_path / f"analytics_dashboard_{timestamp}.md"
    
    print(f"\n📊 Generating Analytics Dashboard...")
    print(f"Output: {report_file}")
    
    # Start building report content
    report = []
    report.append(f"# TradeBot Analytics Dashboard")
    report.append(f"\n**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    report.append("---\n")
    
    # Executive Summary Section
    report.append("## Executive Summary\n")
    report.append(generate_executive_summary())
    report.append("\n---\n")
    
    # System Health Section
    report.append("## System Health\n")
    report.append(generate_system_health())
    report.append("\n---\n")
    
    # Trade Ideas Pipeline Section
    report.append("## Trade Ideas Pipeline\n")
    report.append(generate_trade_ideas_summary())
    report.append("\n---\n")
    
    # Market News Impact Section
    report.append("## Market News Impact\n")
    report.append(generate_news_summary())
    report.append("\n---\n")
    
    # Key Recommendations Section
    report.append("## Actionable Recommendations\n")
    report.append(generate_recommendations())
    report.append("\n---\n")
    
    # Footer
    report.append(f"\n*Report auto-generated by Analytics Dashboard*\n")
    report.append(f"*Data Sources: trade_ideas_log.csv, news_assessments_log.csv, order_history.csv*\n")
    
    # Write to file
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(report))
    
    print(f"✅ Report saved to: {report_file}")
    return report_file


def generate_executive_summary():
    """Generate executive summary section"""
    try:
        news_df = pd.read_csv("../../data/logs/news_assessments_log.csv")
        ideas_df = pd.read_csv("../../data/logs/trade_ideas_log.csv")
        
        total_ideas = len(ideas_df)
        validated = len(ideas_df[ideas_df['Status'] == 'Validated'])
        active = len(ideas_df[ideas_df['Status'] == 'Active'])
        total_news = len(news_df)
        high_sev = len(news_df[news_df['Severity'].isin(['Critical', 'High'])])
        
        summary = []
        summary.append(f"- **Total Trade Ideas**: {total_ideas}")
        summary.append(f"- **Validated Strategies**: {validated}")
        summary.append(f"- **Active Strategies**: {active}")
        summary.append(f"- **Market News Events**: {total_news} ({high_sev} high-severity)")
        summary.append(f"- **Overall Conversion Rate**: {(active/total_ideas*100):.1f}% (Ideas → Active)" if total_ideas > 0 else "- **Overall Conversion Rate**: N/A")
        
        return '\n'.join(summary)
    except Exception as e:
        return f"*Error generating executive summary: {e}*"


def generate_system_health():
    """Generate system health section"""
    try:
        ideas_df = pd.read_csv("../../data/logs/trade_ideas_log.csv")
        ideas_df['Last_Updated'] = pd.to_datetime(ideas_df['Last_Updated'])
        
        now = pd.Timestamp.now()
        ideas_df['days_since_update'] = (now - ideas_df['Last_Updated']).dt.days
        
        stuck = ideas_df[
            (~ideas_df['Status'].isin(['Validated', 'Active', 'Rejected', 'Retired'])) &
            (ideas_df['days_since_update'] > 30)
        ]
        
        health = []
        
        if len(stuck) == 0:
            health.append("✅ **Status**: All systems operating normally")
            health.append("- No stuck ideas in pipeline")
        else:
            health.append(f"⚠️ **Status**: {len(stuck)} ideas need attention")
            health.append(f"- {len(stuck)} ideas stuck for >30 days")
            health.append(f"\n**Stuck Ideas**:")
            for _, idea in stuck.head(5).iterrows():
                health.append(f"- {idea['ID']}: {idea['Name']} ({idea['Status']}, {idea['days_since_update']} days)")
        
        return '\n'.join(health)
    except Exception as e:
        return f"*Error generating system health: {e}*"


def generate_trade_ideas_summary():
    """Generate trade ideas pipeline summary"""
    try:
        ideas_df = pd.read_csv("../../data/logs/trade_ideas_log.csv")
        
        total = len(ideas_df)
        ready = len(ideas_df[ideas_df['Status'] == 'Ready for Backtest'])
        backtesting = len(ideas_df[ideas_df['Status'] == 'Backtesting'])
        validated = len(ideas_df[ideas_df['Status'] == 'Validated'])
        active = len(ideas_df[ideas_df['Status'] == 'Active'])
        rejected = len(ideas_df[ideas_df['Status'] == 'Rejected'])
        
        summary = []
        summary.append("### Pipeline Breakdown")
        summary.append(f"- **Total Ideas**: {total}")
        summary.append(f"- **Ready for Backtest**: {ready} ({ready/total*100:.1f}%)" if total > 0 else "- **Ready for Backtest**: 0")
        summary.append(f"- **Currently Backtesting**: {backtesting}")
        summary.append(f"- **Validated**: {validated} ({validated/total*100:.1f}%)" if total > 0 else "- **Validated**: 0")
        summary.append(f"- **Active (Live)**: {active} ({active/total*100:.1f}%)" if total > 0 else "- **Active**: 0")
        summary.append(f"- **Rejected**: {rejected}")
        
        # By type
        summary.append("\n### By Strategy Type")
        types = ideas_df['Type'].value_counts()
        for strategy_type, count in types.head(5).items():
            summary.append(f"- **{strategy_type}**: {count} ideas")
        
        return '\n'.join(summary)
    except Exception as e:
        return f"*Error generating trade ideas summary: {e}*"


def generate_news_summary():
    """Generate market news impact summary"""
    try:
        news_df = pd.read_csv("../../data/logs/news_assessments_log.csv")
        ideas_df = pd.read_csv("../../data/logs/trade_ideas_log.csv")
        
        total_news = len(news_df)
        with_opp = news_df['Opportunities_Identified'].notna().sum()
        news_driven = len(ideas_df[ideas_df['Notes'].str.contains('NEWS-DRIVEN', case=False, na=False)])
        
        conversion = (news_driven / with_opp * 100) if with_opp > 0 else 0
        
        summary = []
        summary.append(f"- **Total News Events**: {total_news}")
        summary.append(f"- **With Opportunities**: {with_opp}")
        summary.append(f"- **Converted to Trade Ideas**: {news_driven} ({conversion:.1f}%)")
        
        # By category
        summary.append("\n### By News Category")
        categories = news_df['Category'].value_counts()
        for category, count in categories.head(5).items():
            summary.append(f"- **{category}**: {count} events")
        
        return '\n'.join(summary)
    except Exception as e:
        return f"*Error generating news summary: {e}*"


def generate_recommendations():
    """Generate actionable recommendations based on data"""
    try:
        ideas_df = pd.read_csv("../../data/logs/trade_ideas_log.csv")
        news_df = pd.read_csv("../../data/logs/news_assessments_log.csv")
        
        recommendations = []
        
        # Check conversion rate
        total = len(ideas_df)
        active = len(ideas_df[ideas_df['Status'] == 'Active'])
        conversion = (active / total * 100) if total > 0 else 0
        
        if conversion < 10:
            recommendations.append(f"1. **Improve Conversion Rate**: Current rate ({conversion:.1f}%) below target (10%). Review bottlenecks in backtest validation.")
        
        # Check stuck ideas
        ideas_df['Last_Updated'] = pd.to_datetime(ideas_df['Last_Updated'])
        stuck = ideas_df[
            (~ideas_df['Status'].isin(['Validated', 'Active', 'Rejected', 'Retired'])) &
            ((pd.Timestamp.now() - ideas_df['Last_Updated']).dt.days > 30)
        ]
        
        if len(stuck) > 0:
            recommendations.append(f"2. **Clear Pipeline Blockages**: {len(stuck)} ideas haven't progressed in >30 days. Review and either advance or reject.")
        
        # Check news conversion
        with_opp = news_df['Opportunities_Identified'].notna().sum()
        news_driven = len(ideas_df[ideas_df['Notes'].str.contains('NEWS-DRIVEN', case=False, na=False)])
        news_conversion = (news_driven / with_opp * 100) if with_opp > 0 else 0
        
        if news_conversion < 40 and with_opp > 0:
            recommendations.append(f"3. **Increase News Opportunity Capture**: Only {news_conversion:.1f}% of identified opportunities became trade ideas (target: 40%).")
        
        # Check strategy type diversity
        active_types = ideas_df[ideas_df['Status'] == 'Active']['Type'].nunique()
        if active_types < 3:
            recommendations.append(f"4. **Diversify Strategy Types**: Only {active_types} strategy type(s) active. Aim for 3-5 uncorrelated types.")
        
        # Default recommendation if all is well
        if len(recommendations) == 0:
            recommendations.append("✅ **System Operating Optimally**: No critical issues identified. Continue current approach.")
        
        return '\n'.join(recommendations)
    except Exception as e:
        return f"*Error generating recommendations: {e}*"


def print_dashboard_summary():
    """Print dashboard summary to console"""
    print("\n" + "📊" * 30)
    print("ANALYTICS DASHBOARD - QUICK SUMMARY")
    print("📊" * 30)
    
    print("\n" + generate_executive_summary())
    print("\n" + "─" * 60)
    print("\n" + generate_system_health())
    print("\n" + "─" * 60)
    print(generate_recommendations())
    
    print("\n" + "📊" * 30)


def main():
    """Main dashboard generator"""
    print("\n🎯 Analytics Dashboard Generator")
    print("=" * 60)
    
    # Print console summary
    print_dashboard_summary()
    
    # Generate markdown report
    print("\n" + "=" * 60)
    try:
        report_file = generate_markdown_report()
        print(f"\n✅ Full markdown report generated and saved!")
        print(f"📄 View report at: {report_file}")
    except Exception as e:
        print(f"\n❌ Error generating markdown report: {e}")
    
    print("\n" + "=" * 60)


if __name__ == "__main__":
    main()
